name: Build and Release Minecraft Plugin

on:
  push:
    tags:
      - 'v*' # Triggers workflow only on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Adjust Java version if necessary

      # Build the plugin with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Find the correct JAR file (excluding "-reobf")
      - name: Find JAR File
        id: find_jar
        run: |
          JAR_FILE=$(ls build/libs/MinecraftBingo-*.jar | grep -v '-reobf')
          echo "jar_file=$JAR_FILE" >> $GITHUB_ENV

      # Zip the item_data folder
      - name: Zip item_data folder
        run: |
          zip -r item_data.zip item_data

      # Upload build artifacts to the release
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.jar_file }}
            item_data.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
